export const productsData = [
  {
    id: "73423-1",
    displayId: "#73423",
    name: "Product Name",
    category: "Cloth",
    price: "₦40,000",
    vendor: "Sk Ibrahim",
    status: "Publish",
  },
  {
    id: "73423-2",
    displayId: "#73423",
    name: "Product Name",
    category: "Fashion",
    price: "₦40,000",
    vendor: "Jerome Bell",
    status: "Publish",
  },
  {
    id: "73423-3",
    displayId: "#73423",
    name: "Product Name",
    category: "Fashion",
    price: "₦40,000",
    vendor: "Arlene McCoy",
    status: "Publish",
  },
  {
    id: "73423-4",
    displayId: "#73423",
    name: "Product Name",
    category: "Fashion",
    price: "₦40,000",
    vendor: "Albert Flores",
    status: "Publish",
  },
  {
    id: "73423-5",
    displayId: "#73423",
    name: "Product Name",
    category: "Fashion",
    price: "₦40,000",
    vendor: "Jane Cooper",
    status: "Publish",
  },
  {
    id: "73423-6",
    displayId: "#73423",
    name: "Product Name",
    category: "Fashion",
    price: "₦40,000",
    vendor: "Devon Lane",
    status: "Publish",
  },
];
